image: gitpod/workspace-base

tasks:
  - name: Setup requeriments
    command: |
      sudo apt update
      sudo apt upgrade -yq
      sudo apt install -yq python3-pip liblua5.1-0-dev lua5.1
      sudo pip3 install -Uq meson ninja