image: gitpod/workspace-base

tasks:
  - name: Setup requeriments
    init: |
      sudo apt update
      sudo apt upgrade -y
      sudo apt install -y python3-pip liblua5.1-0-dev lua5.1
      sudo pip3 install -U meson ninja pip
