image: gitpod/workspace-base

tasks:
  - name: Setup workspace
    command: |
      sudo apt update
      sudo apt upgrade -yq
      sudo apt install -yq ccls python3-pip liblua5.1-0-dev liblua5.2-dev liblua5.3-dev lua5.1 lua5.2 lua5.3
      sudo pip3 install -Uq meson ninja
      meson _B
      ln -s _B/compile_commands.json

vscode:
  extensions:
    - asabil.meson
    - ccls-project.ccls