image: gitpod/workspace-base

tasks:
  - name: Setup workspace
    command: |
      sudo apt update
      sudo apt upgrade -yq
      sudo apt install -yq ccls python3-pip liblua5.1-0-dev lua5.1
      sudo pip3 install -Uq meson ninja
      meson _B

vscode:
  extensions:
    - asabil.meson
    - ccls-project.ccls