name: Build & Test
on: [push]
jobs:
  ci:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      
      - name: Update packages
        run: |
          sudo apt update
          sudo apt upgrade -yq

      - name: Installing required packages
        run: >
          sudo apt install -yq gcc python3-pip
          lua5.1 lua5.2 lua5.3 lua5.4
          liblua5.1-0-dev liblua5.2-dev liblua5.3-dev liblua5.4-dev

      - name: Installing Meson and Ninja
        run: sudo pip3 install -U meson ninja
        
      - name: Configure using meson
        run: meson setup _BUILD -Dtests=true
      
      - name: Build with Ninja
        run: ninja -vC _BUILD

      - name: Running Meson tests
        run: meson test -C _BUILD