name: Build & Test
on: [push]
jobs:
  ci:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1

      - name: Set up Lua 5.1
        run: sudo apt install -yq lua5.1 liblua5.1-0-dev libreadline-dev libncurses-dev

      - name: Installing Meson and Ninja
        run: pip install meson ninja
        
      - name: Configure using meson
        run: meson . _BUILD
      
      - name: Build with Ninja
        run: ninja -C _BUILD

      - name: Running Meson tests
        run: meson test -C _BUILD